---
minimum_pre_commit_version: 4.5.1

repos:

# commit-msg hooks
# ----------

# Conventional Commit message checker (commitizen)
- repo: https://github.com/commitizen-tools/commitizen
  rev: v4.13.9
  hooks:
  - id: commitizen
    stages:
    - commit-msg

# pre-commit hooks
# ----------

# Standard pre-commit rules
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-toml
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: trailing-whitespace
    args:
    - --markdown-linebreak-ext=md

# Ruff
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.6
  hooks:
  - id: ruff-check
    args:
    - --fix
  - id: ruff-format

# ty type checker.
# Astral's ty is still in pre-release but it's fast (and appears good).
# They don't currently support pre-commit but have suggested that
# it can run locally. The following reproduces what we see by running (ty check).
# Inspired by https://github.com/astral-sh/ty/issues/269
- repo: local
  hooks:
  - id: ty-check
    name: ty check
    entry: uv run ty check
    language: system
    pass_filenames: false
    always_run: true
