---
name: Test

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
  schedule:
  - cron: '8 6 * * *'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.13'
        - '3.14'
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv
      run: pip install uv
    - name: Lint
      run: uv run pre-commit run --all-files
    - name: Help
      run: uv run main.py --help
